### ISSUE TITLE
Simply for loops with .forEach() array method

### ISSUE THREAD

**Issue by jamesmacwhite** [Staples1010/Spot-the-Station-RSS-feed-to-Google-Calendar#1]
Hi! Thanks for this script. I was interested in using it for linking to Home Assistant.

I've read through the code and there's potential optimisation on the for loops. You can use the `forEach()` array method, instead of the traditional JavaScript loop, which is nicer and less code. `forEach()` is supported under Google Apps Script.

When doing this you would need to replace any use of `continue;` to `return` and adjust some of the loop code to not have to do the `array[key]` syntax.

```
items.forEach(item => {
    var title = item.getChildText("title");
    var description = item.getChildText("description");
...
}

**Comment by jamesmacwhite** [comment]
Ignore this! While the loops can be simplified you can't break out of a forEach(), so it would break functionality.

**Comment by PyrokineticDarkElf** [comment]
Hi @jamesmacwhite 👋

I'm glad you like my script! It's probably about time I take another look at it to see if there's any room for optimisation...

**Comment by jamesmacwhite** [comment]
Hi! Thanks for making it, I import the calendar events and then use it to trigger announcements on my Google Mini speaker if the ISS is soon to be overhead and I'm home and it's not an unreasonable time like 3 AM ha ha.

.forEach() is cleaner, but you can't break out of a forEach() conventionally, so that's a bust. These days with ES6, vanilla JavaScript loops look horrible, but sometimes if it works!
